---
title: "P8105 Homework 5"
author: "Xinyu Yang"
date: "11/8/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

```{r}
#introducing missing value:
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

Function and Map:
```{r}
replace_iris_missing = function(x) {
  y = is.numeric(x) & is.na(x)
  z = is.character(x) & is.na(x)
  ifelse(y, round(mean(x, na.rm = TRUE),1), ifelse(z, "virginica", x))
}

#map the above function to vector-column in the dataset
map(.x = as.list(iris_with_missing), ~replace_iris_missing(.x))
```

## Problem 2
```{r}

file_names <- list.files("./data")
read_in = function(x) {
  read_csv("./data/x") 
}
```

```{r message=FALSE}
setwd("./data")
study <-
  file_names %>% 
  set_names() %>% 
  map_dfr(read_csv, .id = "source") %>% 
  separate(source, c("arm","id","a"), sep = "([\\.\\_])") %>% 
  select(id, arm, week_1:week_8) %>% 
  pivot_longer(week_1:week_8, names_to = "week", values_to = "obs_value")

library(viridis)

study %>% 
  separate(week, c("a", "week"), sep = "_") %>% 
  select(-a) %>% 
  ggplot(aes(x = week, y = obs_value, group = id, color = arm)) +
  geom_path() + 
  labs(title = "spaghetti plot of observations on each subject over time") + 
  viridis::scale_color_viridis(
    discrete = TRUE) + 
  theme(legend.position = "right")
```

From the plot we can see .....
(comment the plot)

## Problem 3
```{r}
sim_regression = function(beta1) {
  
  sim_data = tibble(
    x = rnorm(30, mean = 1, sd = 1),
    y = 2 + beta1 * x + rnorm(30, 0, 50)
  )
  
  lm(y ~ x, data = sim_data) %>% 
    broom::tidy() %>% 
    filter(term == "x") %>% 
    select(estimate, p.value) %>% 
    janitor::clean_names()
}

sim_results = 
  tibble(beta_true = c(1:6)) %>% 
  mutate(
    output_lists = map(.x = beta_true, ~rerun(10000, sim_regression(beta1 = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)

#plot1
sim_results %>% 
  mutate(
    reject = ifelse(p_value < 0.05, 1, 0)
  ) %>% 
  group_by(beta_true) %>% 
  summarise(
    n = n(), 
    a = sum(reject)) %>% 
  mutate(p_reject = a/n) %>% 
  ggplot(aes(x = beta_true, y = p_reject)) +
  geom_point() +
  geom_line() +
  scale_x_continuous("True Beta", breaks = c(1:6)) 


#plot2
df_1 <-
  sim_results %>% 
  group_by(beta_true) %>% 
  summarise(all = mean(estimate)) 
df_2 <-
sim_results %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta_true) %>% 
  summarise(reject = mean(estimate))
df_1 %>% 
  inner_join(df_2, by = "beta_true") %>%  
  group_by(beta_true) %>% 
  pivot_longer(all:reject, names_to = "estimate", values_to = "value") %>% 
  ggplot(aes(x = beta_true, y = value, label = round(value,1))) +
  geom_line(aes(color = estimate)) +
  geom_text(vjust = 0, nudge_y = 0.8, aes(color = estimate)) +
  scale_x_continuous("True Beta", breaks = c(1:6))
  
  

```

